### ISSUE TITLE
Add repository_full_name column to the github_search_issue table

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-plugin-github#122]
The `full_name` column is often used in joins across various GitHub tables. It's possible to extract it from one of the existing columns in  `github_search_issue`:

```
  select
    (regexp_matches(url, '.+repos/(.+)/issues'))[1] as repository_full_name,
    *
  from
    github_search_issue
  where
    query = 'is:open is:issue author:judell archived:false'
```

But it would be nicer to have it as a column.

**Comment by ParthaI** [comment]
@judell For making the column name universal, can we use `repository_full_name` instead of `full_name`?

**Comment by judell** [comment]
Sure. I wound up with `full_name` by way of `github_my_repository`, but it appears that `repository_full_name` is much more common.

**Comment by judell** [comment]
Thanks @ParthaI! I should have noticed that the same will apply to other `github_search_*` tables, right?

**Comment by ParthaI** [comment]
Yes, @judell we have a plan to add `repository_full_name` column in other `github_search_*` tables.
