### ISSUE TITLE
Fix doc for github_search_commit table doc

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-github#127]
**Describe the bug**

Due to the difference in the table and table doc file name, the hub has generated 2 entries for the `github_search_commit` table

![image](https://user-images.githubusercontent.com/26873346/148723883-b20090d0-f818-4cc2-957d-a59ab8e51f2d.png)

**Steampipe version (`steampipe -v`)**
Example: v0.11.0

**Plugin version (`steampipe plugin list`)**
Example: v0.10.1

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

https://github.com/turbot/steampipe-plugin-github/blob/main/docs/tables/github_search_commits.md

**Expected behavior**

The name of the file should be the same as the table name. 

**Additional context**

**Comment by judell** [comment]
Heh, I just came here to report that same thing! Thanks for noticing and fixing, @rajlearner17 and @ParthaI.
