### ISSUE TITLE
Query Github Audit Logs - Steampipe

### ISSUE THREAD

**Issue by ngowraj** [turbot/steampipe-plugin-github#164]
**Is your feature request related to a problem? Please describe.**

Create a new table for Github Audit logs for Steampipe. I use this query in our internal tooling to find policy overrides like ["Branch Protection Overrides"](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/reviewing-the-audit-log-for-your-organization#protected_branch-category-actions) to trigger a notification. Would be nice to have this data within Steampipe for us to start using it for security notifications. In addition the Github Audit Logs seems to have other important data like "tokens created, OAuth app creations" which would be useful for finding security gaps. 

curl \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token ghp_...(redacted)" \
  --request GET \
  "https://api.github.com/orgs/loomhq/audit-log?phrase=created:2022-05-10&page=1&per_page=100"

**Describe the solution you'd like**

Able to query github audit logs (https://github.com/organizations/loomhq/settings/audit-log) for the last X days. Differentiating records based on github usernames, event types and timestamps so that it is easy to query and filter results.

**Comment by cbruno10** [comment]
Hey @ngowraj , thanks for opening an issue! FYI I transferred it from the Steampipe CLI repo into the GitHub plugin repo so the issue can get the attention it deserves.

I looked at some of the announcements and API docs for audit logs, and it seems like this API endpoint is only available for GitHub Enterprise Cloud customers. I tried using the same curl command for the `turbot` organization, which is not an enterprise account, and received a "Not Found" error (thought my request could be possibly incorrect):
```
curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ghp_..." --request GET "https://api.github.com/orgs/turbot/audit-log?phrase=created:2022-05-10&page=1&per_page=100"

{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/orgs#get-audit-log"
}
```

Is your organization currently an enterprise account?

**Comment by ngowraj** [comment]
Yes, we are on Enterprise. We also get this data from the UI as well. 
https://github.com/organizations/loomhq/settings/audit-log

**Comment by japborst** [comment]
Interestingly, I can see the audit log for my organization using `https://github.com/organizations/my_org/settings/audit-log` but the API doesn't return anything as we're not on enterprise.

From the [docs](https://docs.github.com/en/rest/enterprise-admin/audit-log#get-the-audit-log-for-an-enterprise):

> To use this endpoint, you must be an enterprise admin, and you must use an access token with the admin:enterprise scope.

**Comment by japborst** [comment]
Opened #166. @ngowraj it would be great if you can help testing it.
