### ISSUE TITLE
In the github_audit_log table, should the `phrase` list qual override any other quals?

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-github#171]
@japborst In the `github_audit_log` table, if a user passes in `created_at` and also specifies `created:` in `phrase`, e.g.,
```
select
  organization,
  actor,
  data
from
  github_audit_log
where
  created_at > now() - interval '30 day'
  and phrase = 'created:2022-01-01 action:protected_branch.policy_override`;
```

I'm not sure what results are returned, maybe an error, or audit log events from either one of the date ranges? In other tables where the API offers a search phrase/filter, e.g., [aws_cloudwatch_log_event](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_cloudwatch_log_event), if a user passes in the search/filter string, that will be used as is and the other quals will be ignored (https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_cloudwatch_log_event.go#L89-L95).

I unfortunately can't test what happens with the current table implementation, but any thoughts on changing the behaviour to be similar to how `aws_cloudwatch_log_event` handles filter conflicts?

**Comment by japborst** [comment]
@cbruno10 this example effectively leads to:
```
'created:2022-01-01 action:protected_branch.policy_override created:>2022-06-09`
```

and that would not lead to any results as both timeframes are exclusive.

In my view, this is expected behaviour, as that's exactly what you're providing in the input. However, if you feel for consistency we should change that, feel free to do so.

**Comment by e-gineer** [comment]
The current behavior of adding other quals to the `phrase` is "correct" / consistent with our approach in other tables & plugins that have a mix of a search qualifier and other qualifiers.

I don't believe that any other combination of ignoring / having precedent fields is easier to understand or produces consistent results.

**Comment by cbruno10** [comment]
@e-gineer Do you happen to recall any other plugins/tables that we use either behaviour in? I found that in the Turbot plugin we do add other quals to the `phrase`, e.g., https://github.com/turbot/steampipe-plugin-turbot/blob/main/turbot/table_turbot_resource.go#L96-L111, but in the CloudWatch log event tables, we set the `FilterPattern` either from the `filter` qual or build it from other quals (https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_cloudwatch_log_event.go#L89-L95). I couldn't find any other examples, though I know we have other tables that support phrases/filters/queries.

If adding other quals is our preferred approach, we can then update the CloudWatch log event tables to be more consistent.

**Comment by e-gineer** [comment]
Sorry - I don't recall right now, and couldn't find with quick searching, but it's definitely the model I've used when doing the quals. I'm surprised the AWS CW Logs tables are done differently, I think they should be aligned with this approach.

**Comment by cbruno10** [comment]
The table doesn't require any updates actually, so the issue being closed as not planned is accurate.
