### ISSUE TITLE
Add table github_compare_commit

### ISSUE THREAD

**Issue by raulsh** [turbot/steampipe-plugin-github#172]
Add compare commit table to  get commits of diff between two commits (tags or branches).

**References**
[1] https://docs.github.com/es/rest/commits/commits#compare-two-commits

**Comment by cbruno10** [comment]
Hey @raulsh , thanks for raising this issue!

For the table, I think creating a table that would take in two commit IDs as required key quals and would return the response information per the API would be an easy to use, intuitive table. I checked the `google/go-github` package we use, and it seems like they support this method already (https://github.com/google/go-github/blob/3a432d62bf0318c14b2d1d7415bf94ea1a884342/github/repos_commits.go#L228-L253).

The table design seems fairly straightforward, so if anyone would like to try creating this table, please let us know and we're happy to collaborate on it! For more information on our coding standards, please see [Table & Column Standards](https://steampipe.io/docs/develop/standards) and [Table Documentation Standards](https://steampipe.io/docs/develop/table-docs-standards).
