### ISSUE TITLE
Add table github_comment

### ISSUE THREAD

**Issue by japborst** [turbot/steampipe-plugin-github#201]
When retrieving issues using `github_issues` table, the url (`comments_url`) and number of comments (`comments`) is exposed. However, I'm missing the actual body of the comments.

**References**
https://docs.github.com/en/rest/issues/comments

**Comment by cbruno10** [comment]
Hey @japborst , thanks for opening this request!

The API docs you linked seem pretty straightforward, so I've attached a `help wanted` label to the issue, and if anyone would like to try creating a new table called `github_issue_comment`, we'd be happy to help out!

**Comment by japborst** [comment]
Perhaps if it's a rainy weekend, I'll write it. Should be straight forward, indeed.

**Comment by wedwardbeck** [comment]
I too am looking for a comments table.  Since people comment freely on issues in our use, but fail to use labels correctly, it's easier to filter down results using key phrase searches.  
Have you been able to make any progress on this front?

**Comment by cbruno10** [comment]
Hi @wedwardbeck , I'll let @japborst provide any updates on his end, but from our end we haven't done any work on this table yet. If you are interested in working on it, we're happy to help in any way we can!

**Comment by japborst** [comment]
Still a valid issue; not stale

**Comment by cbruno10** [comment]
Added into `main` branch as part of https://github.com/turbot/steampipe-plugin-github/pull/280
