### ISSUE TITLE
Add table github_projectsv2

### ISSUE THREAD

**Issue by pigmej** [turbot/steampipe-plugin-github#202]
**References**
https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects

I'm especially mentioning the projectsv2, not the classic ones.

**Comment by misraved** [comment]
Hey @pigmej, thanks for opening this feature request!

If anyone would like to attempt developing this table, the API @pigmej  linked is a great place to start. The table should be fairly straightforward, but if anyone has questions, please let us know!
