### ISSUE TITLE
onboarding flow breaks with: `zsh: parse error near `\n'`

### ISSUE THREAD

**Issue by breck7** [turbot/steampipe-plugin-github#203]
<img width="370" alt="Screen Shot 2022-09-30 at 6 06 28 AM" src="https://user-images.githubusercontent.com/74692/193311612-77cd9af7-f69a-404b-abc6-0b665486e000.png">

**Comment by breck7** [comment]
NM I'm the dumbest person in world

**Comment by breck7** [comment]
Actually I'm only bottom 10% dumbest. Every other step I could copy/paste but obviously this one I have to edit:

<img width="1019" alt="Screen Shot 2022-09-30 at 6 07 56 AM" src="https://user-images.githubusercontent.com/74692/193311860-12b99620-ce30-4f10-9d61-e776b8430f04.png">

**Comment by breck7** [comment]
I suggest updating (https://hub.steampipe.io/plugins/turbot/github) by adding `steampipe query` so people that don't read like me can then just copy/paste the sample sql query.

**Comment by breck7** [comment]
Also, I think you can use GitHub with very slow rate limiting without an API key. That would make the first use experience much better, and then your users can add their Creds later when they need to run it at scale.

<img width="1146" alt="Screen Shot 2022-09-30 at 6 09 54 AM" src="https://user-images.githubusercontent.com/74692/193312302-d29d3e76-da38-4692-8c51-25efb0067d6f.png">

**Comment by breck7** [comment]
Perhaps your copy/paste example should be:

`export GITHUB_TOKEN=YOURTOKENHERE
steampipe query
select
  name,
  language,
  forks_count,
  stargazers_count
from
  github_my_repository;`

**Comment by breck7** [comment]
This is soooo cool. Thanks steampipe!

<img width="537" alt="Screen Shot 2022-09-30 at 6 16 37 AM" src="https://user-images.githubusercontent.com/74692/193313321-4db7bab8-9886-4f62-9f5d-8bd9d51eb1c9.png">

**Comment by breck7** [comment]
https://github.com/turbot/steampipe-plugin-github/pull/204

**Comment by cbruno10** [comment]
@breck7 Glad to see you got your queries up and running! I've merged in https://github.com/turbot/steampipe-plugin-github/pull/204, so I'll go ahead and close this issue, but if you have any other questions, please let us know!
