### ISSUE TITLE
Querying github_audit_log with repo field fails with "cannot unmarshal array into Go struct field AuditEntry.repo of type string"

### ISSUE THREAD

**Issue by asfaltboy** [turbot/steampipe-plugin-github#218]
**Describe the bug**

When executing the query as below, it fails and returns this error:

```
Warning: executeQueries: query 1 of 1 failed: ERROR: rpc error: code = Unknown desc = json: cannot unmarshal array into Go struct field AuditEntry.repo of type string (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
0.16.4

**Plugin version (`steampipe plugin list`)**
0.22.1

**To reproduce**

Create a query which retruns events where the repo field returns an array:
```sql
-- get_audit_log.sql
select
  id,
  created_at,
  actor,
  action,
  repo
from
  github_audit_log
where
  organization = 'my-org'
  and created_at between '2022-08-01' and '2022-11-08'
order by
  created_at
```
execute the query
```sh
steampipe query get_audit_log.sql
```

**Expected behavior**

Should handle the repo field type correctly

**Additional context**

I imagine there are some audit log results for which this works, I tried setting `include` field to `git` and `web`, but both returned the error for me.

**Comment by cbruno10** [comment]
Hey @ngowraj, have you seen this issue before with any of your queries? I remember that you had created the audit log table, and unfortunately we still don't have access to GitHub Enterprise, so any feedback/test results you have would be immensely helpful here, thanks!
