### ISSUE TITLE
Add table github_saml_identity

### ISSUE THREAD

**Issue by olafz** [turbot/steampipe-plugin-github#228]
**Introduction**
When you have enabled SAML single sign-on for your GitHub enterprise account, each enterprise member can link their external identity on your identity provider to their existing account on GitHub.com. Steampipe's existing capability allows for querying external identity providers, like [Azure AD](https://hub.steampipe.io/plugins/turbot/azuread). To be able to map GitHub account names onto centrally managed identities, the proposed new table `github_saml_identity` will be tremendously helpful: it will allow to query the single sign-on identity that a member has linked to their account on GitHub.com.

**References**
- GitHub documentation: https://docs.github.com/en/enterprise-cloud@latest/admin/user-management/managing-users-in-your-enterprise/viewing-and-managing-a-users-saml-access-to-your-enterprise
- GitHub GraphQL API documentation: https://docs.github.com/en/graphql/reference/objects#externalidentity

**Comment by olafz** [comment]
This GraphQL query will - more or less - provide you with the data to populate the table:

```
{{
   organization(login: [[Organisation name]]) {{
     samlIdentityProvider {{
       ssoUrl
       externalIdentities {{
         edges {{
           cursor
           node {{
             guid
             samlIdentity {{
               nameId
             }}
             user {{
               login
             }}
           }}
         }}
       }}
     }}
   }}
 }}
```

**Comment by misraved** [comment]
Welcome to Steampipe @olafz and thanks for raising this issue including the necessary documentation links 👍.

**Comment by olafz** [comment]
This issue is still relevant ;) The feature requests still stands.

**Comment by olafz** [comment]
> @olafz - would you be comfortable building the plugin from source and testing out a table to support this feature?

Absolutely. I'll have to schedule some time to do so. I hope to be able to give you some feedback before the end of this week.

**Comment by olafz** [comment]
Hi @graza-io!

I've been able to briefly test the plugin and it's a great start 🎉 I do have some feedback based on my early testing to make it even better.

First, one of the columns is called `user`:

```
> .inspect github_organization_external_identity
+-------------------------+-------+------------------------------------------------------------+
| column                  | type  | description                                                |
+-------------------------+-------+------------------------------------------------------------+
(...)
| user                    | jsonb | The GitHub user account.                                   |
(...)
+-------------------------+-------+------------------------------------------------------------+
```

It took me a while to realize that this actually a reserved word, which causes confusion:

```
> select user from github_organization_external_identity where organization = '...';
+-----------+
| user      |
+-----------+
| steampipe |
| steampipe |
| steampipe |
| steampipe |
(...)
```

instead of 

```
> select "user" from github_organization_external_identity where organization = '...';
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| user                                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
(...)
| {"created_at":"2009-05-04T09:56:08Z","email":"","id":80709,"login":"olafz","name":"Olaf van Zandwijk","node_id":"...","updated_at":"2023-06-08T08:12:28Z","url":"https://github.com/olafz"}                                                                         |
(...)
```

I guess it also depends on environmental (auto-quoting) settings, but to prevent confusion, it might be an idea to rename the field `user` to something else (`github_user` ?).

More of an issue is that `guid` seems to be empty, always?

```
> select
  guid,
  "user" ->> 'login' as user_login,
  saml_identity ->> 'username' as saml_user
from
  github_organization_external_identity
where
  organization = '...';

+--------+----------------- ---+----------------------------+
| guid   | user_login          | saml_user                  |
+--------+---------------------+----------------------------+
| <null> | <redacted>          | <redacted>                 |
| <null> | <redacted>          | <redacted>                 |
| <null> | <redacted>          | <redacted>                 |
| <null> | <redacted>          | <redacted>                 |
| <null> | <redacted>          | <redacted>                 |
| <null> | <redacted>          | <redacted>                 |
| <null> | <redacted>          | <redacted>                 |
```

Again, it's a great start and I'll definitively play around a bit more with it and try it in a real-world situation. Also, when there is a new version I'm happy to test that as well!

**Comment by graza-io** [comment]
Hey @olafz thanks for the feedback!

I'll look to get this addressed by end of this week - will update you here when I have something else ready for testing.

**Comment by olafz** [comment]
Thanks for the update, great job!

> Hopefully resolved the issue with `guid`

Yes, it did 👍 

```
> select
  guid,
  user_login
from
  github_organization_external_identity
where
  organization = '...';

+--------------------------------------+-----------------------+
| guid                                 | user_login            |
+--------------------------------------+-----------------------+
(...)
| <redacted>                           | olafz                 |
(...)
```

`user_login` is a great addition and `user_detail` also works as expected now. The only thing I can't verify, is the `scim_identity`. We don't use that, so it's not possible for me to test. That means it's empty for me:
```
> select
  guid,
  user_login,
  saml_identity ->> 'username' as saml_user,
  scim_identity ->> 'username' as scim_user,
  organization_invitation ->> 'role' as invited_role
from
  github_organization_external_identity
where
  organization = '...';

+--------------------------------------+-----------------------+------------------------------------------+-----------+--------------+
| guid                                 | user_login            | saml_user                                | scim_user | invited_role |
+--------------------------------------+-----------------------+------------------------------------------+-----------+--------------+
| <redacted>                           | olafz                 | <redacted>                               |           |              |
(...)
```

**Comment by graza-io** [comment]
Excellent, thanks for the rapid feedback!

I'll throw up a PR for these changes :)
