### ISSUE TITLE
Update github_tag table to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#238]
Is your feature request related to a problem? Please describe.
I'd like to use the GraphQL API when querying the table

Describe the solution you'd like
Update the table to use the GraphQL API

Describe alternatives you've considered
N/A

Additional context

For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
  - `tagger_date` - date the tag was created if available
  - `tagger_name` - name of the user whom created the tag. (null if custom `tag_message` set)
  - `message` - message associated with the tag.
  - `commit` - JSON column for nested commit

Removed columns
  - `zipball_url` - embedded in `commit`
  - `tarball_url` - embedded in `commit`
  - `commit_sha` - embedded in `commit`
  - `commit_url` - embedded in `commit`

Columns with data changes (please include examples of old and new data for each entry)
  - All urls now point to web app rather than REST API endpoints.

**Comment by graza-io** [comment]
Commit: [e9368e0](https://github.com/turbot/steampipe-plugin-github/commit/e9368e0c0c77bb00b70e55ac15718bd2355449d3) on `graphql-dev` branch.

**Comment by graza-io** [comment]
Commit: [c5997e9](https://github.com/turbot/steampipe-plugin-github/commit/c5997e93d7f7b6b9d712ebcb49627a837603d124) on `graphql-branch`

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
