### ISSUE TITLE
Update github_release table to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#240]
Is your feature request related to a problem? Please describe.
I'd like to use the GraphQL API when querying the table

Describe the solution you'd like
Update the table to use the GraphQL API

Describe alternatives you've considered
N/A

Additional context

For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns

- ?

Removed columns

- ?

Columns with data changes (please include examples of old and new data for each entry)

- ?

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
