### ISSUE TITLE
Update github_team & github_my_team tables to use GraphQL API 

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#241]
Is your feature request related to a problem? Please describe.
I'd like to use the GraphQL API when querying the table

Describe the solution you'd like
Update the table to use the GraphQL API

Describe alternatives you've considered
N/A

Additional context

For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
- `created_at` - was commented out previously as not supported, now it is.
- `updated_at` - was commented out previously as not supported, now it is. 
- `combined_slug` - The slug corresponding to the organization and the team.
- `ancestors_total_count` - count of ancestors.
- `child_teams_total_count` - count of child teams.
- `discussions_count` - count of discussions.
- `invitations_count` - count of pending members invited but not yet processed.
- `projects_v2_count` - count of v2 projects the team has.
- `avatar_url` - url for teams avatar.
- `discussions_url` - url for teams discussions.
- `edit_teams_url` - url for editing the team.
- `teans_url` - url to get teams that belong to this team.
- `can_administer` - indicates if logged in user can administer the team.
- `can_subscribe` - indicates if logged in user can subscribe to the team.
- `subscription` - the subscription status of logged in user to the team.

Removed columns
- `organization_id`
- `organization_login` - would be a dupe of `organization`.
- `organization_type` - not included on GraphQL API but also seems to be `Organization`.
- `permission` - not included on GraphQL API.
- `html_url` - Would be a duplicate of `url`

Renamed Columns
- `repos_count` => `repositories_count`
- `parent` => `parent_team`

Columns with data changes (please include examples of old and new data for each entry)
- `url` - changed from REST API endpoint to web ui url (formerly `html_url`)
- `members_url` - changed from REST API endpoint to web ui url
  - Old: `https://api.github.com/organizations/38865304/team/1234567/members{/member}`
  - New: `https://github.com/orgs/turbot/teams/my-team/members`
- `repositories_url` - changed from REST API endpoint to web ui url
  - Old: `https://api.github.com/organizations/38865304/team/1234567/repos`
  - New: `https://github.com/orgs/turbot/teams/my-team/repositories`
- `parent_team` (prev:`parent`) - addition of `node_id` to JSON
  - Old: `{"id":1234, "slug":"my-team", "name":"My Team"}`
  - New: `{"name": "My Team", "slug": "my-team", "id": 1234, "node_id": "4togryvotu3qr"}`
- `privacy` - updated response values  as per [these docs](https://docs.github.com/en/graphql/reference/enums#teamprivacy) (if required, this can be adjusted to previous values via a transform)
  - Old: `closed` or `secret`
  - New: `VISIBLE` or `SECRET`

**Comment by graza-io** [comment]
Commit [3b97ed1](https://github.com/turbot/steampipe-plugin-github/commit/3b97ed1dab7c8a1ddaf0792beb543f69da4285c0) on `graphql-dev` branch

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
