### ISSUE TITLE
Update github_branch table to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#244]
Is your feature request related to a problem? Please describe.
I'd like to use the GraphQL API when querying the table

Describe the solution you'd like
Update the table to use the GraphQL API

Describe alternatives you've considered
N/A

Additional context

For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
- `commit` - JSON column of the commit.
- `branch_protection_rule` - JSON column of branch protection rule.

Removed columns
- `commit_sha` - now nested in `commit`
- `commit_url` - now nested in `commit`

Columns with data changes (please include examples of old and new data for each entry)
- None

**Comment by graza-io** [comment]
Commit [86130a3](https://github.com/turbot/steampipe-plugin-github/commit/86130a3ff87ed1b21948f373c710a872715bfed8) on `graphql-dev`

**Comment by graza-io** [comment]
Commit [c5997e9](https://github.com/turbot/steampipe-plugin-github/commit/c5997e93d7f7b6b9d712ebcb49627a837603d124) on `graphql-dev` branch.

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
