### ISSUE TITLE
Update github_user table to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#248]
Is your feature request related to a problem? Please describe.
I'd like to use the GraphQL API when querying the table

Describe the solution you'd like
Update the table to use the GraphQL API

Describe alternatives you've considered
N/A

Additional context

For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
- `any_pinnable_items`
- `estimated_next_sponsors_payout_in_cents`
- `has_sponsors_listing`
- `interaction_ability`
- `is_bounty_hunter`
- `is_campus_expert`
- `is_developer_program_member`
- `is_employee`
- `is_following_you`
- `is_github_star`
- `is_hireable`
- `is_sponsoring_you`
- `is_you`
- `monthly_estimated_sponsors_income_in_cents`
- `pinned_items_remaining`
- `projects_url`
- `pronouns`
- `sponsors_listing`
- `status`
- `can_changed_pinned_items`
- `can_create_projects`
- `can_follow`
- `can_sponsor`
- `is_following`
- `is_sponsoring`
- `issues_total_count`
- `organizations_total_count`
- `public_keys_total_count`
- `open_pull_requests_total_count`
- `merged_pull_requests_total_count`
- `closed_pull_requests_total_count`
- `packages_total_count`
- `pinned_items_total_count`
- `sponsoring_total_count`
- `sponsors_total_count`
- `starred_repositories_total_count`
- `watching_total_count`

Renamed columns
- `hireable` => `is_hireable`
- `site_admin` => `is_site_admin`
- `html_url` => `url`
- `blog` => `website_url`
- `public_repos` => `public_repositories_total_count`
- `public_gists` => `public_gists_total_count`
- `total_private_repos` => `private_repositories_total_count`
- `disk_usage` => `repositories_total_disk_usage`
- `followers` => `followers_total_count`
- `following` => `following_total_count`

Removed columns
- `url` - previous `url` was removed and replaced by renaming `html_url` to `url`
- `gravatar_url` - field doesn't appear in GraphQL response.
- `private_gists` - causes a permissions error (even though only attempting to pull back a count).
- `collaborators` - unsure what this field is meant to indicate but couldn't find a matching field in the GraphQL.
- `two_factor_authentication` - haven't figured out how to obtain this yet (in v3 only returned value for logged in user and null for other users)
- `ldap_dn` - field doesn't appear to be obtainable yet in GraphQL.

Columns with data changes (please include examples of old and new data for each entry)
- None

**Comment by graza-io** [comment]
Commit: [f9fbe14](https://github.com/turbot/steampipe-plugin-github/commit/f9fbe1428843c267b3ba3ef9d7f9971d522bc203) on `graphql-dev` branch

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
