### ISSUE TITLE
Update github_branch_protection table to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#251]
Is your feature request related to a problem? Please describe.
I'd like to use the GraphQL API when querying the table

Describe the solution you'd like
Update the table to use the GraphQL API

Describe alternatives you've considered
N/A

Additional context

For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
- `id` - numeric id of the rule
- `node_id` - string identifier of the rule
- `matching_branches` - a count of branches which this rule applies to.
- `blocks_creations` - a bool indicating is branch creation is a protected operation.
- `creator_login` - login of the user whom created the rule.
- `dismisses_stale_reviews` - bool indicating if new commits pushed to matching branches dismiss pull request review approvals.
- `lock_allows_fetch_and_merge` - a bool indicating if users can pull changes from upstream when the branch is locked.
- `lock_branch` - a bool indicating if branches are read-only and cannot be pushed to.
- `pattern` - the branch protection rule pattern.
- `require_last_push_approval` - a bool indicating if the most recent push must be approved by someone other than the person who pushed it.
- `requires_approving_reviews` - a bool indicating if approving reviews required to update matching branches.
- `required_approving_review_count` -  a count of how many reviews are required.
- `requires_code_owner_reviews` - a bool indicating if reviews from code owners are required to update matching branches.`
- `requires_deployments` - a bool indicating if matching branches require deployment to specific environments before merging.
- `required_deployment_environments` - a list of required deployment environments that must be deployed to successfully to update matching branches.
- `requires_status_checks` - a bool indicating if status checks are required to update matching branches.
- `requires_strict_status_checks` - a bool indicating if branches are required to be up to date before merging.
- `restricts_pushes` - a bool indicating if pushing to matching branches is restricted to Apps, Users & Teams identified in the `push_allowance_*` columns.
- `bypass_force_push_allowance_apps` - list of apps which can force push.
- `bypass_force_push_allowance_teams` - list of users which can force push.
- `bypass_force_push_allowance_users` - list of users which can force push.
- `bypass_pull_request_allowance_apps` - list of apps which can bypass PRs.
- `bypass_pull_request_allowance_teams` - list of teams which can bypass PRs.
- `bypass_pull_request_allowance_users` - list of users which can bypass PRs.

Removed columns
- `name` - we're pulling all for the repo, not just those from specific branches, therefore this field no longer exists.
- `required_pull_request_reviews` - indirectly replaced, was a JSON object now two columns a bool indicating if required `requires_approving_reviews` & an int count `required_approving_review_count`

Renamed Columns (Old => New)
- `enforce_admins_enabled` => `is_admin_enforced`
- `allow_deletions_enabled` => `allows_deletions`
- `allow_force_pushes_enabled` => `allows_force_pushes`
- `required_conversation_resolution_enabled` => `requires_conversation_resolution`
- `required_linear_history_enabled` => `requires_linear_history`
- `signatures_protected_branch_enabled` => `requires_commit_signatures`
- `restrictions_apps` => `push_allowance_apps`
- `restrictions_teams` => `push_allowance_teams`
- `restrictions_users` => `push_allowance_users`

Columns with data changes (please include examples of old and new data for each entry)
- `push_allowance_apps` (previously `restrictions_apps`) has a redefined (simpler) JSON structure comprising of `slug` and `name`.
- `push_allowance_teams` (previously `restrictions_teams`) has a redefined (simpler) JSON structure comprising of `slug` and `name`.
- `push_allowance_users` (previously `restrictions_users`) has a redefined (simpler) JSON structure comprising of `login` and `name`.

**Comment by graza-io** [comment]
Commit: [a6f651d](https://github.com/turbot/steampipe-plugin-github/commit/a6f651d6f577ddfd55c7ed87e61d6cd123cf0d7a) in `graphql-dev` branch.

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
