### ISSUE TITLE
Update github_team_repository table to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#254]
**Is your feature request related to a problem? Please describe.**
I'd like to use the GraphQL API when querying the table

**Describe the solution you'd like**
Update the table to use the GraphQL API

**Describe alternatives you've considered**
n/a

**Additional context**
For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
- `primary_language` 
- `code_of_conduct`
- `license_info`
- `default_branch_ref`
- `allow_update_branch` 
- `archived_at`
- `auto_merge_allowed`
- `contact_links`
- `forking_allowed`
- `funding_links`
- `has_discussions_enabled`
- `has_vulnerability_alerts_enabled`
- `interaction_ability`
- `is_blank_issues_enabled`
- `is_empty`
- `is_in_organization`
- `is_locked`
- `is_mirror`
- `is_security_policy_enabled`
- `is_user_configuration_repository`
- `issue_templates`
- `lock_reason`
- `merge_commit_message`
- `merge_commit_title`
- `mirror_url`
- `name_with_owner`
- `open_graph_image_url`
- `projects_url`
- `pull_request_templates`
- `security_policy_url`
- `squash_merge_commit_message`
- `squash_merge_commit_title`
- `uses_custom_open_graph_image`
- `can_administer`
- `can_create_projects`
- `can_subscribe`
- `can_update_topics`
- `has_starred`
- `temp_clone_token`
- `possible_commit_emails`
- `subscription`
- `your_permission`
- `web_commit_signoff_required`

Removed columns
- `language` - contained  within `primary_language`
- `code_of_conduct_key` - contained within `code_of_conduct`
- `code_of_conduct_name` - contained within `code_of_conduct`
- `code_of_conduct_url` - contained within `code_of_conduct`
- `collaborators` - collab to new table
- `collaborator_logins` - collab to new table
- `outside_collaborators` - collab to new table
- `outside_collaborator_logins` - collab to new table
- `license_key` - contained within `license_info`
- `license_name` - contained within `license_info`
- `license_node_id` - contained within `license_info`
- `license_spdx_id` - contained within `license_info`
- `license_url` - contained within `license_info`
- `clone_url` 
- `default_branch` - string value replaced by `default_branch_ref`
- `git_url` 
- `owner_id`
- `owner_type`
- `template_repository`

Renamed columns
- `private` => `is_private`
- `html_url` => `url`
- `archived` => `is_archived`
- `stargazers_count` => `stargazer_count`
- `disabled` => `is_disabled`
- `fork` => `is_fork`
- `forks_count` => `fork_count`
- `size` => `disk_usage`
- `homepage` => `homepage_url`
- `has_issues` => `has_issues_enabled`
- `has_projects` => `has_projects_enabled`
- `has_wiki` => `has_wiki_enabled`
- `allow_merge_commit` => `merge_commit_allowed`
- `allow_rebase_merge` => `rebase_merge_allowed`
- `allow_squash_merge` => `squash_merge_allowed`
- `watchers_count` => `watchers_total_count`
- `open_issues_count` => `open_issues_total_count`
- `permissions` => `permission`

Columns with data changes
- `permission` (formerly `permissions`) now is a fixed string with highest permission given rather than a JSON collection of permissions acquired.

**Comment by graza-io** [comment]
https://github.com/turbot/steampipe-plugin-github/commit/9fcbd73f2fd31e11a741d872fcc2667e4e6756e9

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
