### ISSUE TITLE
Update github_issue & github_my_issue tables to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#260]
**Is your feature request related to a problem? Please describe.**
I'd like to use the GraphQL API when querying the table

**Describe the solution you'd like**
Update the table to use the GraphQL API

**Describe alternatives you've considered**
n/a

**Additional context**
For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
- `active_lock_reason`
- `author`
- `body_url`
- `closed`
- `created_via_email`
- `editor`
- `full_database_id`
- `includes_created_edit`
- `is_pinned`
- `is_read_by_user`
- `last_edited_at`
- `milestone`
- `published_at`
- `state_reason`
- `user_can_close`
- `user_can_react`
- `user_can_reopen`
- `user_can_subscribe`
- `user_can_update`
- `user_cannot_update_reasons`
- `user_did_author`
- `user_subscription`
- `assignees_total_count`
- `labels_total_count`

Renamed columns
- `issue_number` => `number`
- `comments` => `comments_total_count`

Removed columns
- `assignee_logins` - pageable response, should be moved to another table.
- `comments_url` - rest api endpoint.
- `events_url` - rest api endpoint.
- `html_url` - now moved to `url`
- `labels` - pageable response.
- `labels_url` - rest api endpoint.
- `milestone_id` - now included in `milestone`
- `milestone_title` - now included in `milestone`
- `repository_url` - rest api endpoint.
- `reactions` - pageable response
- `tags`

Columns with data changes
- `url` now contains content previously found in `html_url` instead of a rest api endpoint.

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
