### ISSUE TITLE
Update github_commit table to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#262]
**Is your feature request related to a problem? Please describe.**
I'd like to use the GraphQL API when querying the table

**Describe the solution you'd like**
Update the table to use the GraphQL API

**Describe alternatives you've considered**
n/a

**Additional context**
For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
- `short_sha`
- `author`
- `committer`
- `additions`
- `deletions`
- `changed_files`
- `committed_via_web`
- `commit_url` 
- `signature`
- `status`
- `tarball_url`
- `zipball_url`
- `tree_url`
- `can_subscribe`
- `subscription`

Renamed columns
- `author_date` => `authored_date`
- `committer_date` => `committed_date`

Removed columns
- `verified` - information can now be found in the `signature` column JSON.
- `comments_url`
- `commit` 
- `files`
- `html_url`
- `parents`
- `stats` - now individual columns

Columns with data changes
- `url` now has contents of previous fields `html_url` instead of rest api endpoint

**Comment by graza-io** [comment]
https://github.com/turbot/steampipe-plugin-github/pull/263/commits/95f5bf4e738de5a1340c3c3bc39bf7ae84d80373

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
