### ISSUE TITLE
Update github_workflow table to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#264]
**Is your feature request related to a problem? Please describe.**
I'd like to use the GraphQL API when querying the table

**Describe the solution you'd like**
Update the table to use the GraphQL API

**Describe alternatives you've considered**
n/a

**Additional context**
For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
- `line_count`
- `size`
- `language`
- `is_truncated`
- `is_binary`
- `is_generated`
- `commit_sha`
- `commit_url`

Renamed columns
- `workflow_file_content` => `text`
- `workflow_file_content_json` => `text_json`

Removed columns
- `id`
- `badge_url`
- `created_at`
- `updated_at`
- `html_url`
- `state`
- `url`

Columns with data changes
- None

**Comment by graza-io** [comment]
https://github.com/turbot/steampipe-plugin-github/commit/a9eb6712b905adba26f633818a8a8ec2400304cb

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
