### ISSUE TITLE
Update github_community_profile table to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#266]
**Is your feature request related to a problem? Please describe.**
I'd like to use the GraphQL API when querying the table

**Describe the solution you'd like**
Update the table to use the GraphQL API

**Describe alternatives you've considered**
n/a

**Additional context**
For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

New columns
- None

Renamed columns
- `issue_template` => `issue_templates`
- `pull_request_template` => `pull_request_templates`
- `license` => `license_info`

Removed columns
- `health_percentage`
- `updated_at`

Columns with data changes
- `code_of_conduct` - updated json
- `contributing` - updated json
- `license_info` (formerly `license`) now has more info in updated JSON.
- `readme` - updated json
- `security` - updated json

**Comment by graza-io** [comment]
Now on `graphql-dev` branch

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
