### ISSUE TITLE
Update github_search_issue, github_search_pull_request, github_search_repository, github_search_user tables to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#268]
Is your feature request related to a problem? Please describe.
I'd like to use the GraphQL API when querying the search tables

Describe the solution you'd like
Update the tables to use the GraphQL API

Describe alternatives you've considered
n/a

Additional context
For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

## Notes:

- All `text_matches` columns will be updated to new JSON data format
  - Old Format: `[{"matches": [{"text": "steampipe", "indices": [0, 9]}], "fragment": "steampipe-plugin-github", "property": "name", "object_url": "https://api.github.com/repositories/331646306", "object_type": "Repository"}]`
  - New Format: `[{"fragment": "steampipe-plugin-github", "property": "name.camel", "highlights": [{"text": "steampipe", "end_indice": 9, "begin_indice": 0}]}, {"fragment": "steampipe-plugin-github", "property": "name", "highlights": [{"text": "steampipe", "end_indice": 9, "begin_indice": 0}]}]`

**Comment by graza-io** [comment]
Now on `graphql-dev` branch

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
