### ISSUE TITLE
Update github_stargazer & github_my_star tables to use GraphQL API

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#270]
**Is your feature request related to a problem? Please describe.**
I'd like to use the GraphQL API when querying the table

**Describe the solution you'd like**
Update the table to use the GraphQL API

**Describe alternatives you've considered**
n/a

**Additional context**
For any fields that have paging, consider implementing that field as another table to avoid excess API calls (as per https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion).

### github_star_gazer
New columns
- `user`

Renamed columns
- None

Removed columns
- None

Columns with data changes
- None

### github_my_star
New columns
- `url`

Renamed columns
- None

Removed columns
- None

Columns with data changes
- None

**Comment by graza-io** [comment]
Now on `graphql-dev` branch

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
