### ISSUE TITLE
New github_rate_limit_graphql table.

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#272]
**Is your feature request related to a problem? Please describe.**
The current rate limit table only considers the REST API limits.

**Describe the solution you'd like**
I'd like a new table to obtain the GraphQL rate limit information.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by graza-io** [comment]
Now on `graphql-dev` branch

**Comment by cbruno10** [comment]
Completed in https://github.com/turbot/steampipe-plugin-github/commit/43238350007bb67f6489a6b5620d95c580feeabb
