### ISSUE TITLE
table github_user missing name field

### ISSUE THREAD

**Issue by ahlfors** [turbot/steampipe-plugin-github#293]
**Describe the bug**
Table github_user missing name field.
executeQueries: query 1 of 1 failed: ERROR: column "name" does not exist (SQLSTATE 42703)

**Plugin version (`steampipe plugin list`)**
main branch after this commit: https://github.com/turbot/steampipe-plugin-github/commit/42680ef98590141ff40251fdc9175336454c75b5

**To reproduce**
1. run steampipe plugin install github
2. steampipe query "select name from github_user where login='cbruno10'"

**Expected behavior**
Query return with name field successfully.

**Comment by graza-io** [comment]
Ah, thanks for catching this & the quick PR!

I've attached relevant code review requests to the PR.
