### ISSUE TITLE
bypass_pull_request_allowance_* is not populated.

### ISSUE THREAD

**Issue by misterek** [turbot/steampipe-plugin-github#297]
**Describe the bug**
The list of teams/people "Allow specified actors to bypass required pull requests" does not appear to be populated.

**Steampipe version (`steampipe -v`)**
Steampipe v0.20.7

**Plugin version (`steampipe plugin list`)**
0.28.1 (Also installed from repo)

**To reproduce**
Select "Allow specified actors to bypass required pull requests" in branch protections. Add a user to the list.  Then
`steampipe query "select default_branch_ref from github_my_repository where name=reponame"`
(I see the same results with github_repository)

**Expected behavior**
Expect "bypass_pull_request_allowance_users" or "bypass_pull_request_allowance_teams" to be populated somewhere. (https://github.com/turbot/steampipe-plugin-github/blob/main/github/table_github_branch_protection.go#L58)

**Additional context**
It appears as if it's supposed to happen here: https://github.com/turbot/steampipe-plugin-github/blob/main/github/table_github_branch_protection.go#L305

If anyone can confirm, I can attempt to take a look when I have time, though I'm unfamiliar with the GraphQL API. 

For reference, this is the specific feature I am referring to: https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/

**Comment by graza-io** [comment]
Hi @misterek - sorry to hear you're hitting issues!

Ideally, yes the `github_branch_protection` table would be used to get the information on branch protections, whilst some is available directly from the repo table for convenience, we omitted including anything which would need to page nested resources to obtain data such as users/apps/teams which can bypass PR for force push rules, etc.

I added myself to the relevant section on a repo as a test:
![Screenshot 2023-07-07 at 13 56 24](https://github.com/turbot/steampipe-plugin-github/assets/53316123/7fd3cd45-5f06-4360-be2f-15ce8ec37441)

When querying the results I can see I am correctly added there.
<img width="847" alt="Screenshot 2023-07-07 at 13 53 26" src="https://github.com/turbot/steampipe-plugin-github/assets/53316123/615f33c7-ecf8-4cf8-aaa9-3a00fa770e7f">

If you're seeing anything different would you be able to confirm your membership level on the repository in question as well as that your GH PAT has the following permissions:
`gist, read:org, read:user, repo, user:email`

**Comment by misterek** [comment]
Interesting!  Apparently I was looking at the completely wrong table.    When querying github_branch_protection, I _do_ see it there.

I think what I'd maybe say is it's slightly confusing, because when querying "default_branch_ref", it includes a number of branch protection rules (and is actually labeled "branch_protection_rule").  But, I'm now seeing that that's an incomplete set of branch protection rules.

Anyway, I am completely unblocked and will close this issue. Thank yo so much!
