### ISSUE TITLE
Add labels/tags to issue/PR tables.

### ISSUE THREAD

**Issue by graza-io** [turbot/steampipe-plugin-github#298]
**Context**
@judell mentioned that since we migrated to the GraphQL SDK that he is missing the `tags` from the issue tables, upon inspection these appear to just be parsed variants of the `labels` returned by the APIs.

However, it appears that we omitted the labels & instead included a `labels_total_count` field on the following tables due to labels being a paginated nested resource:
- `github_my_issue`
- `github_issue`
- `github_pull_request`

**Describe the solution you'd like**
Since the expected number of labels on a typical issue / PR would be less than a single API page (100), it makes sense to obtain the first page of labels in the aforementioned tables as a nested item (JSON Column), this approach may mean that we have edge cases where an issue or PR which has in-excess of 100 labels may be missing the data from the column on the table.

**Alternative Solution**
Implement as a separate table that can be joined onto when labels are required (`github_issue_label`, `github_pull_request_label`) - this approach would ensure we don't miss data, but to obtain labels for a collection of issues/PRs would incur `n` x rate limit credit usage where `n` is number of issues/PRs.

**Additional context**
Both are valid approaches as per the [Design Principals](https://github.com/turbot/steampipe-utils/wiki/GraphQL-Plugin-Design-Principals) - @cbruno10 primarily looking for your preferred approach and I can implement that.

**Comment by cbruno10** [comment]
@graza-io I agree, adding a `labels` column to the issue/PR tables is OK as an exception in this case, because it's unlikely (and may not even be possible, I couldn't find a limit anywhere in GitHub docs) that more than 100 labels would be attached to a single issue or PR.

**Comment by graza-io** [comment]
@judell - I've pushed some code to the `298-labels` branch that should add in column `labels` to the issue/PR tables.

This is a JSON type column and data will be similar to:
`[{"color":"a2eeef","description":"New feature or request","is_default":true,"name":"enhancement","node_id":"MDU6TGFiZWwyNjc2MDI0NTUy"}, {"color":"006b75","description":"New table request","is_default":false,"name":"new table","node_id":"MDU6TGFiZWwyODQ2NDM2NTUw"}]`

If you could try it out and let me know if this satisfies your requirements?

**Comment by judell** [comment]
Thanks @graza-io. I didn't actually need the tags, just happened to have included them, which was handy because it alerted us to their absence. I'm glad they're finding their way back, and I'll give the branch a try.
