### ISSUE TITLE
Github Enterprise 404s

### ISSUE THREAD

**Issue by annettejanewilson** [turbot/steampipe-plugin-github#305]
**Describe the bug**
All queries against Github Enterprise v3.8.3 return empty results. Looking at the logs, Steampipe is receiving 404s.

The problem appears to be the trailing `/` that Steampipe [attaches to the connection URL][1].

[1]: https://github.com/turbot/steampipe-plugin-github/blob/7b4c2b37c3acae1cff2c0a74bbb3146678dfe407/github/utils.go#L120

**Steampipe version (`steampipe -v`)**
v0.20.9

**Plugin version (`steampipe plugin list`)**
built from source, commit 7b4c2b37c3acae1cff2c0a74bbb3146678dfe407

**To reproduce**
Configure base_url to point to a GHE server.

```
base_url = "https://github.enterprise.example"
```

Make a query, e.g.

```
select * from github_my_repository limit 1
```

**Expected behavior**
A row is returned.

**Actual behavior**
No rows are returned. Logs show an error:
```
github_repository: api_error="non-200 OK status code: 404 Not Found body: \"{\\"message\\":\\"Not Found\\",\\"documentation_url\\":\\"http
s://docs.github.com/enterprise-server@3.8/graphql\\"}\""
```

**Additional context**
Even with this fixed, Github Enterprise does not work - no published Github Enterprise version's GraphQL schema includes the `archivedAt` field. I still cannot get results successfully, the logs contain errors like:

```
[
    "{Field 'archivedAt' doesn't exist on type 'Repository' [{1 179}]}",
    "{Field 'requiredDeploymentEnvironments' doesn't exist on type 'BranchProtectionRule' [{1 571}]}",
    "{Field 'requiresDeployments' doesn't exist on type 'BranchProtectionRule' [{1 758}]}",
    "{Field 'fundingLinks' doesn't exist on type 'Repository' [{1 1002}]}",
    "{Field 'hasVulnerabilityAlertsEnabled' doesn't exist on type 'Repository' [{1 1087}]}",
    "{Field 'interactionAbility' doesn't exist on type 'Repository' [{1 1144}]}"
]
```

I'll raise this as a [separate bug][#306].

[#306]: https://github.com/turbot/steampipe-plugin-github/issues/306

**Comment by graza-io** [comment]
Thanks for pointing this out!

I've submitted a PR to remove the trailing slash from the url.
