### ISSUE TITLE
Queries fail on GHE due to missing fields

### ISSUE THREAD

**Issue by annettejanewilson** [turbot/steampipe-plugin-github#306]
**Describe the bug**
Queries against Github Enterprise fail 

**Steampipe version (`steampipe -v`)**
v0.20.9

**Plugin version (`steampipe plugin list`)**
built from source, commit 7b4c2b37c3acae1cff2c0a74bbb3146678dfe407

**Github enterprise version**
v3.8.3

**To reproduce**
* Get commit 7b4c2b37c3acae1cff2c0a74bbb3146678dfe407
* Remove [the trailing slash][1] on the `api/graphql/` path. (See #305.)
* Build.
* Configure base_url to point to a GHE server.
* Perform a query. For example, I'm doing this:
```
select full_name, description from github_repository where full_name = 'mshell/mshell-tools'
```

[1]:  https://github.com/turbot/steampipe-plugin-github/blob/7b4c2b37c3acae1cff2c0a74bbb3146678dfe407/github/utils.go#L120

**Expected behavior**
The query succeeds and returns a result.

**Actual behavior**
The query returns no results and the logs show:
```
[
    "{Field 'archivedAt' doesn't exist on type 'Repository' [{1 179}]}",
    "{Field 'requiredDeploymentEnvironments' doesn't exist on type 'BranchProtectionRule' [{1 571}]}",
    "{Field 'requiresDeployments' doesn't exist on type 'BranchProtectionRule' [{1 758}]}",
    "{Field 'fundingLinks' doesn't exist on type 'Repository' [{1 1002}]}",
    "{Field 'hasVulnerabilityAlertsEnabled' doesn't exist on type 'Repository' [{1 1087}]}",
    "{Field 'interactionAbility' doesn't exist on type 'Repository' [{1 1144}]}"
]
```

**Additional context**
Github Enterprise lags behind the [public GraphQL API][schema-main]. You can verify that these fields don't exist in the [Enterprise 3.8 GraphQL schema][schema38]. At least archivedAt doesn't exist in [Enterprise 3.9][schema39] either, which is the latest currently available. If Github Enterprise is to be supported, there would need to be some way either to limit to an older schema or to cope with these fields not being present. I'm not familiar enough with GraphQL to know the options here, or if there's good tooling to catch this sort of thing automatically. I can see it being pretty impractical to maintain by hand if you don't have access to a GHE instance.

[schema-main]: https://docs.github.com/en/graphql/overview/public-schema
[schema38]: https://docs.github.com/en/enterprise-server@3.8/graphql/overview/public-schema
[schema39]: https://docs.github.com/en/enterprise-server@3.9/graphql/overview/public-schema

**Comment by graza-io** [comment]
@annettejanewilson thanks for raising this issue, certainly wasn't aware that the latest Enterprise Server lagged that far behind [Enterprise Cloud](https://docs.github.com/en/enterprise-cloud@latest/graphql/reference/objects#repository) which is where I think we did our comparison.

I'll raise this internally so we can devise how we want to approach this & update thread when we have a direction.

**Comment by graza-io** [comment]
Hey @annettejanewilson, just wanted to give you a quick update.

We're still trying to decide on the best approach to rework the plugin to have support for Enterprise Server.

In the meantime, if you're struggling to query data, you could always revert your plugin to a version prior to the GraphQL updates (pure REST): `steampipe plugin install github@0.27.0` and this should provide more stability for the short-term.

**Note**: You'll need to utilise the `.inspect` functionality to verify column names and also if you're utilising any mods, downgrade them to version which support the older plugin.

We understand this approach might not be ideal; we're just suggesting this as a short-term solution to have support for querying Enterprise Server in the interim.

**Comment by cbruno10** [comment]
In order to handle removing unsupported fields, I think one approach could be modifying our GraphQL queries based on the columns we receive in the query.

One potential blocker though is https://github.com/turbot/steampipe-plugin-sdk/issues/555. For instance, if a user runs `select full_name, description from github_repository where full_name = 'mshell/mshell-tools'`, we should only submit those GraphQL fields in the API request. We can do that today, but for other columns like `issue_templates`, which the query didn't request, will be stored as `null` in the cache.

**Comment by cbruno10** [comment]
Hey @annettejanewilson , we just released v0.34.0 of this plugin, which updates the repository tables to only request fields that are included in the `select` statement.

We still don't have a good way in the plugin to tell you which fields are supported in your particular version, but if you don't include unsupported fields in the query now, the queries should complete.

Can you please try running queries against any of the repository tables you were trying before and let us know if they complete OK now? Thanks!

**Comment by graza-io** [comment]
This table should work with 3.9 & 3.10.

It will also work for 3.8 with exception of the `default_branch_ref` column, as this will still attempt to obtain the following fields (which are only included in 3.9 onwards) from the embedded protection rule:
- `requiresDeployments`
- `requiredDeploymentEnvironments`

**Comment by bigdatasourav** [comment]
@annettejanewilson, did you get a chance to try out the above? Could you please share if it successfully resolved the issue you were experiencing?

**Comment by bigdatasourav** [comment]
Hey, @annettejanewilson, we're closing this issue as we have not heard back from you; please feel free to re-open if you want to share anything. Also, apart from the repository tables, we are updating all the other [tables](https://github.com/turbot/steampipe-plugin-github/pulls) to request the select columns only, which may be able to resolve your issue. Thanks!
