### ISSUE TITLE
Include triggering_actor in GitHub Workflow Runs

### ISSUE THREAD

**Issue by julioz** [turbot/steampipe-plugin-github#314]
**Is your feature request related to a problem? Please describe.**
We have a few workflows internally we'd like to aggregate metrics on. One of them is "who is the person who mostly triggers it per week?".

**Describe the solution you'd like**
The GitHub API for workflow runs [includes](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#get-a-workflow-run) `triggering_actor` as a field, and so does the GitHub Actions workflows UI.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by graza-io** [comment]
@julioz 

If you do some comparative testing, is the `triggering_actor` usually different from the `actor`?

I can see we don't include either at the current moment in time, however based on the SDK we're using to obtain the data, they don't seemingly have a concept of `triggering_actor` only `actor` [struct here](https://github.com/google/go-github/blob/master/github/actions_workflow_runs.go#L16-L49).

**Comment by julioz** [comment]
I believe that, for my specific use-case, `actor` should work fine, although `triggering_actor` can be different.

According to [this post](https://github.blog/changelog/2022-07-19-differentiating-triggering-actor-from-executing-actor/) on when GitHub introduced the differentiation, a workflow will have a `actor` that is not the `triggering_actor` when it is a _rerun_.

That is:

1. Workflow W is executed by User A
2. Workflow W fails
3. Workflow W is executed by User T

In this case, `actor` = A, `triggering_actor` = T.

**Comment by graza-io** [comment]
Did some investigation, have now requested the relevant data be included in the `go-gitlab` SDK on this [issue](https://github.com/google/go-github/issues/2874)

**Comment by julioz** [comment]
Thanks. Looking forward to this change (except I think you mean `go-github` and not `go-gitlab`).

**Comment by graza-io** [comment]
SDK v54.0.0 contains the new field on struct - assuming no other breaking changes we should now be able to action this request.

**Comment by graza-io** [comment]
Looking at the breaking changes in versions between current and v54, only one stands out as potential issue:
- [Issue](https://github.com/google/go-github/issues/2645)/[PR](https://github.com/google/go-github/pull/2646) which changes all `time.Time` to internal type `Timestamp`, we do have the translation code for these so should be simple as updating where required.

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-github/pull/332

Thanks @julioz and @graza-io for all the work 👍 !!
