### ISSUE TITLE
Querying workflow runs does not return all results

### ISSUE THREAD

**Issue by julioz** [turbot/steampipe-plugin-github#315]
**Describe the bug**
I have a GitHub repository with thousands of action runs.
When querying `github_actions_repository_workflow_run` for successful ones, only a subset of the expected rows are returned.

**Steampipe version (`steampipe -v`)**
Example:  v0.20.10

**Plugin version (`steampipe plugin list`)**
Example: v0.30.2

**To reproduce**
Notice I am selecting `id` and ordering by `created_at` to see how far back the results give:
```
select id,created_at from github_actions_repository_workflow_run where workflow_id='<ID>' and repository_full_name = '<REPO_ID>' and conclusion='success' ORDER BY created_at DESC LIMIT 1000;
```

**Expected behavior**
Up to 1000 rows (according to `LIMIT` set).

**Expected behavior**
Only 37 are returned, from the past week:
```
+------------+---------------------------+
| id         | created_at                |
+------------+---------------------------+
| 58748905 | 2023-08-15T15:12:29+02:00 |
| 58120515 | 2023-08-15T01:01:37+02:00 |
| 5862156 | 2023-08-14T22:12:11+02:00 |
| 585854583 | 2023-08-14T19:17:58+02:00 |
| 585192803 | 2023-08-14T16:49:06+02:00 |
| 58124477 | 2023-08-14T16:42:05+02:00 |
| 585537064 | 2023-08-14T14:13:23+02:00 |
| 585521993 | 2023-08-14T13:36:14+02:00 |
| 58548067 | 2023-08-14T12:47:43+02:00 |
| 58531130 | 2023-08-14T09:37:22+02:00 |
| 583668375 | 2023-08-11T22:15:58+02:00 |
| 583642231 | 2023-08-11T21:41:40+02:00 |
| 583626502 | 2023-08-11T21:20:03+02:00 |
| 58362224 | 2023-08-11T21:13:58+02:00 |
| 583614513 | 2023-08-11T21:05:16+02:00 |
| 58354779 | 2023-08-11T19:41:38+02:00 |
| 58354427 | 2023-08-11T19:36:39+02:00 |
| 58351707 | 2023-08-11T19:05:51+02:00 |
| 58350966 | 2023-08-11T18:57:37+02:00 |
| 58334575 | 2023-08-11T16:01:22+02:00 |
| 583334448 | 2023-08-11T15:48:30+02:00 |
| 583307033 | 2023-08-11T15:18:09+02:00 |
| 58316948 | 2023-08-11T12:44:52+02:00 |
| 58316836 | 2023-08-11T12:43:08+02:00 |
| 58315013 | 2023-08-11T12:21:38+02:00 |
| 583080723 | 2023-08-11T11:02:47+02:00 |
| 583070463 | 2023-08-11T10:50:14+02:00 |
| 583069387 | 2023-08-11T10:48:48+02:00 |
| 583056658 | 2023-08-11T10:33:07+02:00 |
| 582947292 | 2023-08-11T08:07:44+02:00 |
| 582348469 | 2023-08-10T18:08:45+02:00 |
| 582118682 | 2023-08-10T14:40:08+02:00 |
| 582111599 | 2023-08-10T14:33:08+02:00 |
| 582022139 | 2023-08-10T12:59:02+02:00 |
| 582017918 | 2023-08-10T12:53:40+02:00 |
| 582013876 | 2023-08-10T12:48:45+02:00 |
| 582013548 | 2023-08-10T12:48:25+02:00 |
+------------+---------------------------+
```

My expectation was for several other rows to be included.

**Additional context**
N/A

**Comment by graza-io** [comment]
@julioz I am able to replicate a similar behaviour

If I run:
```sql
select count(*) as total 
from github_actions_repository_workflow_run 
where repository_full_name = 'turbot/steampipe';
```
```
+-------+
| total |
+-------+
| 5853  |
+-------+
```

If I limit this to one particular workflow ID and one particular conclusion type (`success`)
```sql
select count(*) as total
from github_actions_repository_workflow_run
where repository_full_name = 'turbot/steampipe'
and workflow_id = '0000000000'
and conclusion = 'success';
```
```
+-------+
| total |
+-------+
| 239   |
+-------+
```

If I then add on the `limit` of `1000` it seems to give me less results:
```sql
select count(*) as total
from github_actions_repository_workflow_run
where repository_full_name = 'turbot/steampipe'
and workflow_id = '43647634'
and conclusion = 'success' limit 1000;
```
```
+-------+
| total |
+-------+
| 217   |
+-------+
```

If you drop the `limit` from your query, are you obtaining all the expected results?

**Comment by julioz** [comment]
Unfortunately not, if I drop the `LIMIT` I still get reduced results (in fact, the same as when I set `LIMIT 1000`).

**Comment by graza-io** [comment]
In this case, if you call the API with the same restrictions do you also get the same results?

**Comment by julioz** [comment]
I have tried running a similar query using github.com/cli/cli and with that I obtain the expected results (i.e a more complete list than what steampipe returns).

**Comment by graza-io** [comment]
> Unfortunately not, if I drop the LIMIT I still get reduced results (in fact, the same as when I set LIMIT 1000).

@julioz - apologies, did you attempt this with the cache disabled? (`.cache off` in interactive mode).

**Comment by julioz** [comment]
Same, even with `.cache off` 😢

**Comment by graza-io** [comment]
Ah ok, it just occurred to me when I was testing something else today and the cache gave me results I wasn't expecting that maybe your query was pulling data from cache when you tested.

If that's not the case I'm pretty stumped as to why your CLI would return different from Steampipe as they both use the API under the hood.

**Comment by graza-io** [comment]
@julioz would you be able to provide some debug logs for your queries.

In order to do this you would need to set the environment variable `STEAMPIPE_LOG_LEVEL` to `DEBUG` [docs](https://steampipe.io/docs/reference/env-vars/steampipe_log)

Then if you enter Steampipe in interactive mode using `steampipe query`

and input the following replacing <workflow> and <repo> with relevant identifiers:
```
.cache off

.timing on

select count(id) from github_actions_repository_workflow_run where repository_full_name = '<repo>' and workflow_id = '<workflow>' and conclusion = 'success';

select count(id) from github_actions_repository_workflow_run where repository_full_name = '<repo>' and workflow_id = '<workflow>' and conclusion = 'success' limit 1000;
```

If you'd be so kind as to share back both the STDOUT output from this and the plugin logs from `~/.steampipe/logs` this may help to debug your issue.

**Comment by julioz** [comment]
```
> .cache off
> .timing off
> .timing on
> select count(id) from github_actions_repository_workflow_run where repository_full_name = 'gradle/ge' and workflow_id = '52859611' and conclusion = 'success';
+-------+
| count |
+-------+
| 20    |
+-------+

Time: 35.2s. Rows fetched: 1,000. Hydrate calls: 0.
```

```
> select count(id) from github_actions_repository_workflow_run where repository_full_name = 'gradle/ge' and workflow_id = '52859611' and conclusion = 'success' limit 1000;
+-------+
| count |
+-------+
| 20    |
+-------+

Time: 31.6s. Rows fetched: 1,000. Hydrate calls: 0.
```

[plugin-2023-09-27.log](https://github.com/turbot/steampipe-plugin-github/files/12739784/plugin-2023-09-27.log)

**Comment by graza-io** [comment]
Thanks, are you expecting more than `20` results in the `1000` results (are you expecting more than 1000 total?)

Unfortunately the plugin logs haven't been helpful in this case, almost feel like we need to increase the logging to we do in the table.

It does indeed seem strange that you obtain exactly `1000` rows both times.

```
> select count(id) from github_actions_repository_workflow_run where repository_full_name = 'turbot/steampipe' and workflow_id = '19441004';
+-------+
| count |
+-------+
| 371   |
+-------+

Time: 178.9s. Rows fetched: 4,202. Hydrate calls: 0.
```

```
> select count(id) from github_actions_repository_workflow_run where repository_full_name = 'turbot/steampipe' and workflow_id = '19441004' limit 1000;
+-------+
| count |
+-------+
| 371   |
+-------+

Time: 155.9s. Rows fetched: 4,203. Hydrate calls: 0.
```

(I checked and there was a workflow run on the repository between my queries)

From the 4200+ returned results I get only 371 match the `workflow_id` passed in, this is filtered post-API calls.

Are you able to obtain a count of expected returned rows using something akin to:
```
gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/OWNER/REPO/actions/runs | jq ' .total_count'
```

For example:
```
❯ gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/turbot/steampipe/actions/runs | jq ' .total_count'
4203
```

**Comment by julioz** [comment]
I think what you mean is the number of workflow runs for that given workflow ID, right? Listing all workflow runs in the repository won't match exactly what I queried above.

Here is the GitHub API return:
```
$ gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/<repo>/actions/workflows/<workflow_id>/runs | jq .total_count
11871
```

**Comment by bigdatasourav** [comment]
Hey @julioz, We are closing this issue as we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
