### ISSUE TITLE
YAML unmarshal error in `github_workflow.pipeline` column

### ISSUE THREAD

**Issue by tsibley** [turbot/steampipe-plugin-github#329]
**Describe the bug**
When querying some (but not all) repos with `github_workflow`, I get:

```
Error: failed to populate column 'pipeline': yaml: unmarshal errors:
  line 112: cannot unmarshal !!str `${{ tru...` into bool (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
Steampipe v0.20.11

**Plugin version (`steampipe plugin list`)**
```
+-----------------------------------------------+---------+-------------+
| Installed Plugin                              | Version | Connections |
+-----------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/github@latest | 0.31.0  | github      |
| hub.steampipe.io/plugins/turbot/net@latest    | 0.9.0   | net         |
+-----------------------------------------------+---------+-------------+
```
**To reproduce**
```sql
select
    pipeline
from
    github_workflow
where
        repository_full_name = 'tsibley/github-actions-testing'
    and id = 68827315
;
```

**Expected behavior**
No error.

**Additional context**
I believe this is triggered by https://github.com/argonsecurity/pipeline-parser/ (as used by this plugin) being unable to handle GitHub Actions workflow interpolation for the `continue-on-error` key of a job. See [my test case workflow](https://github.com/tsibley/github-actions-testing/blob/master/.github/workflows/steampipe-parse-failure.yaml) for the reproduction above. However, GitHub's documentation makes it clear that [interpolation can be used in that key](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability) and indeed we have valid workflows which do so.

**Comment by tsibley** [comment]
Ah, this looks fixed in the upstream package with https://github.com/argonsecurity/pipeline-parser/commit/c8904c0def1af66b6cd149c984584b5295f6016c, part of v0.3.2 onwards. This plugin is using v0.1.16 though, it seems.

**Comment by tsibley** [comment]
I'm having similar issues with other workflow fields that https://github.com/argonsecurity/pipeline-parser/ doesn't properly parse, like the following:

```yaml
on:
  repository_dispatch:
    types: my-custom-event-name
```

since it doesn't recognize `repository_dispatch` and makes a generic "Event" object for it which declares `types` as `[]string`:

https://github.com/argonsecurity/pipeline-parser/blob/main/pkg/loaders/github/models/trigger.go#L45-L50

**Comment by graza-io** [comment]
Hey @tsibley - apologies you're hitting these issues & you're correct they do stem from a third-party library we're using.

I have already created an [issue](https://github.com/argonsecurity/pipeline-parser/issues/78) in the relevant repo highlighting this, which I see you've also found and extended with more information, thanks 🙏🏻.

I'll look to update our plugin to a more recent version of the pipeline parser this week, albeit I know this won't solve all issues it may help you with a few particular fields.

As you've stated you don't need the `pipeline` field for your work an alternative interim solution could also be to build the plugin locally from source after commenting out the [column](https://github.com/turbot/steampipe-plugin-github/blob/main/github/table_github_workflow.go#L51) - should this be a route for you to take, the `Makefile` in the repository is currently configured to output into the default install location for plugins.
- Comment out column
- Ensure no running Steampipe instances
- Run `make` from plugin root dir
- Ensure built successfully
- Query Steampipe!

**Comment by tsibley** [comment]
@graza-io Thanks! It hadn't occurred to me to build the plugin locally, but that makes sense. For now I've worked around the issues by explicitly excluding the triggering [repos](https://github.com/nextstrain/status/blob/7075eeb22846cbca4ed565e0b5cdf2e699257569/workflow-runs.sql#L24-L36)/[workflows](https://github.com/nextstrain/status/blob/7075eeb22846cbca4ed565e0b5cdf2e699257569/workflow-runs.sql#L48-L58) in my queries—luckily, I don't need to include them—but building locally would let me simplify the queries (albeit at the expense of more complex setup/install) or handle cases where I _can't_ exclude the triggering workflows. I appreciate the suggestion!

**Comment by graza-io** [comment]
@tsibley - next plugin release should contain `pipeline-parser` updated to `v0.3.3` - we did want to go higher but ran into issues outlined [here](https://github.com/turbot/steampipe-plugin-github/pull/330#issuecomment-1715750596) if you're interested.
