### ISSUE TITLE
GitHub v3 API fields cause error in `github_search_repository` table

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-github#336]
**Describe the bug**
If I run a query trying to get any v3 API fields, I get this error:
```sql
> select topics from github_search_repository where query = 'repo:turbot/.github'

Error: rpc error: code = Internal desc = hydrate function hydrateRepositoryDataFromV3 failed with panic interface conversion: interface {} is struct { TextMatches []models.TextMatch; Node struct { models.Repository "graphql:\"... on Repository\"" } }, not models.Repository (SQLSTATE HV000)

+--------+
| topics |
+--------+
+--------+
```

**Steampipe version (`steampipe -v`)**
v0.20.9

**Plugin version (`steampipe plugin list`)**
v0.33.0

**To reproduce**
See above

**Expected behavior**
Results should be returned or those columns should not be available in the `github_search_repository` table if not compatible

**Additional context**

**Comment by graza-io** [comment]
Ah, some oversight on my part, should be relatively easy to resolve.
