### ISSUE TITLE
502 Bad Gateway with repos with large amount of  PRs

### ISSUE THREAD

**Issue by cirpo** [turbot/steampipe-plugin-github#351]
**Describe the bug**
Getting `Error: non-200 OK status code: 502 Bad Gateway body: "{\n   \"data\": null,\n   \"errors\":[\n      {\n         \"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug.`

on repo with a big number of PRs (> 80k)

**Steampipe version (`steampipe -v`)**
0.21.1
**Plugin version (`steampipe plugin list`)**
0.35.1

**To reproduce**
You can try it with `kubernetes/kubernetes` repo that has >75k PRs

```sql
select
  author,
  number,
  title,
  state
from
  github_pull_request
where
  repository_full_name = 'kubernetes/kubernetes'
  and state = 'OPEN'
  and created_at >= (current_date - interval '7' day)
```

**Expected behavior**
I'm expecting results

**Additional context**
In some cases, queries seems working, especially when the `where` clause is simple, like

```sql
select
  author,
  number,
  title,
  state
from
  github_pull_request
where
  repository_full_name = 'kubernetes/kubernetes'
```
I get results but *also* the `Error: non-200 OK status code: 502 Bad Gateway body: "{\n   \"data\": null,\n   \"errors\":[\n      {\n         \"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug` error.

is it related only to Gihub APIs?

thanks

**Comment by cbruno10** [comment]
This issue will be addressed once https://github.com/turbot/steampipe-plugin-github/pull/342 is merged, which reduces the number of fields we send to the GitHub API.
