### ISSUE TITLE
Strange behavior: "Variable $includeAllowUpdateBranch is used by anonymous query"

### ISSUE THREAD

**Issue by Z4ck404** [turbot/steampipe-plugin-github#376]
**Describe the bug**

This returns an error : 

```
SELECT
 gtm.organization,
 gtm.slug AS team_slug,
 gtm.login,
 gtm.role,
 gtr.name,
 gtr.permission,
 gtr.is_fork,
 gtr.is_private
FROM
 github_team_member gtm
JOIN
 github_team_repository gtr ON gtm.slug = gtr.slug AND gtm.organization = gtr.organization
WHERE
 gtm.organization = 'orgName'
 AND gtm.slug IN (
  'team-a',
  'team-b'
 )
 AND gtr.name  IN (
  'repoA',
  'repoB'
 )
```

`Error: Variable $includeAllowUpdateBranch is used by anonymous query but not declared (SQLSTATE HV000)` 

but this works : 
```

SELECT
 gtm.organization,
 gtm.slug AS team_slug,
 gtm.login,
 gtm.role,
 gtr.name,
 gtr.permission,
 gtr.is_fork,
 gtr.is_private
FROM
 github_team_member gtm
JOIN
 github_team_repository gtr ON gtm.slug = gtr.slug AND gtm.organization = gtr.organization
WHERE
 gtm.organization = 'orgName'
 AND gtm.slug IN (
  'team-a',
  'team-b'
 )
 AND gtr.name  IN (
  gtr.name = 'repoA' OR
  gtr.name = 'repoB'
 )
```

**Steampipe version (`steampipe -v`)**
Steampipe v0.21.1

**Plugin version (`steampipe plugin list`)**
0.36.0

**To reproduce**
Run the query above.

**Expected behavior**

**Additional context**

**Comment by rajlearner17** [comment]
@Z4ck404, Thanks for using Steampipe and reporting this issue. 

We have a fix available [here](https://github.com/turbot/steampipe-plugin-github/pull/379).ETA this week/early next week.

If you want to try it, here are a few steps to test this, PR branch. 

- [Install Go](https://go.dev/doc/install)
- Clone the repo `git clone git@github.com:turbot/steampipe-plugin-github.git` and `cd steampipe-plugin-github`
- Check out the PR branch `git checkout team_repo`
- Execute the make command to compile -  `make`
- Execute the the same query you mentioned in Steampipe Query prompt

Feel free to get back to us.
CC @bigdatasourav
