### ISSUE TITLE
Using a Github App token with Steampipe doesn't work

### ISSUE THREAD

**Issue by xcambar** [turbot/steampipe-plugin-github#390]
**Describe the bug**
My company wants to setup a Steampipe instance and we want to avoid to use a Personal Access Token, but rather use an existing (private) Github App.

The token we used in Steampipe was generated following the GH docs [here](https://clarkworld.slack.com/archives/C068GDKFVAP/p1701878981824609) and [here](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app).

**Steampipe version (`steampipe -v`)**

`Steampipe v0.21.1`

**Plugin version (`steampipe plugin list`)**

```
+--------------------------------------------------+---------+-------------+
| Installed                                        | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/github@latest    | 0.38.0  | github      |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.9.1   | steampipe   |
+--------------------------------------------------+---------+-------------+
```

**To reproduce**
1. Generate a token for a Github App, with ALL permissions set to `read`
2. `GITHUB_TOKEN="ghs_xxxxxx" steampipe query "select * from github_organization_member  where organization='YOUR_ORG'"`. 
3. It fails with the following error: `Error: Resource not accessible by integration (SQLSTATE HV000)`

**Expected behavior**
It should return the list of members of the organization that the app is installed in.

**Additional context**
As said above, in my attempts to make it work, I've maxed out the permissions of the application.
Here's the full list of permissions of the app and associated token:

```json
{
  "token": "ghs_xxx",
  "expires_at": "2023-12-07T09:15:06Z",
  "permissions": {
    "members": "read",
    "organization_actions_variables": "read",
    "organization_administration": "read",
    "organization_announcement_banners": "read",
    "organization_codespaces": "read",
    "organization_codespaces_secrets": "read",
    "organization_codespaces_settings": "read",
    "organization_copilot_seat_management": "read",
    "organization_custom_org_roles": "read",
    "organization_custom_properties": "read",
    "organization_custom_roles": "read",
    "organization_dependabot_secrets": "read",
    "organization_events": "read",
    "organization_hooks": "read",
    "organization_personal_access_tokens": "read",
    "organization_personal_access_token_requests": "read",
    "organization_plan": "read",
    "organization_projects": "read",
    "organization_secrets": "read",
    "organization_self_hosted_runners": "read",
    "organization_user_blocking": "read",
    "team_discussions": "read",
    "actions": "read",
    "actions_variables": "read",
    "administration": "read",
    "checks": "read",
    "codespaces": "read",
    "codespaces_lifecycle_admin": "read",
    "codespaces_metadata": "read",
    "codespaces_secrets": "write",
    "contents": "read",
    "dependabot_secrets": "read",
    "deployments": "read",
    "discussions": "read",
    "environments": "read",
    "issues": "read",
    "merge_queues": "read",
    "metadata": "read",
    "packages": "read",
    "pages": "read",
    "pull_requests": "read",
    "repository_advisories": "read",
    "repository_hooks": "read",
    "repository_projects": "read",
    "secrets": "read",
    "secret_scanning_alerts": "read",
    "security_events": "read",
    "statuses": "read",
    "vulnerability_alerts": "read",
    "workflows": "write"
  },
  "repository_selection": "all"
}
```

**Comment by xcambar** [comment]
I guess this overlaps #311 at least partly, looking at the discussion.

**Comment by cbruno10** [comment]
The SDK should support using an app, not sure what the config args look like though, https://github.com/google/go-github?tab=readme-ov-file#as-a-github-app.

**Comment by badideasforsale** [comment]
I would also like to use this plugin for a Pipes installation at my company. A PAT is linked to my access, which is a problem if I don't work there anymore, or it expires, etc.

+1 from me to supporting app-based auth in this plugin, thanks!

**Comment by ParthaI** [comment]
Hello @xcambar, thank you for your patience.

I've made several updates in the `issue-390` branch to resolve the issue, particularly to enable GitHub App authentication. The configuration file now allows for the inclusion of `app_id`, `installation_id`, and `private_key`. You can also set these values using the environment variables `GITHUB_APP_ID`, `GITHUB_INSTALLATION_ID`, and `GITHUB_PRIVATE_KEY`.

Here's a sample of what the `~/.steampipe/config/github.spc` file should look like now:

```hcl
connection "github" {
  plugin          = "github"
  app_id          = 803263
  installation_id = 29384756
  private_key     = "/Users/path-to-private-key/testappsetting.2024-01-18.private-key.pem"
}
```

The Steampipe GitHub plugin follows this order for authentication:

1. Token authentication using the `GITHUB_TOKEN` environment variable, if set.
2. Token authentication using the `token` configured in `~/.steampipe/config/github.spc`, if `GITHUB_TOKEN` is not set.
3. GitHub App authentication using the relevant environment variables.
4. GitHub App authentication using credentials provided in the `~/.steampipe/config/github.spc` file.

I'd greatly appreciate it if you would like to test these changes in the PR branch `issue-390` and share your feedback.

Here are the steps to try it out:

- Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-github.git`
- Change directory: `cd steampipe-plugin-github`
- Switch to the branch: `git checkout issue-390`
- Update the `.spc` file or set the environment variables as needed.
- Run the command: `make`
- Execute your queries

Thank you!

**Comment by ParthaI** [comment]
Hello @xcambar, I hope you are doing great. Have you had the opportunity to review the previous comment?

**Comment by xcambar** [comment]
Hi. I quickly tested during the week, but since the results were inconclusive (read: the request failed), I need to investigate a bit more to find out if something wrong's on my side (configuration etc.) so I can come back with more useful data.

**Comment by MichaelBurgess** [comment]
@ParthaI this approach is reasonable if you are able to access the GH app private key from where you define the connection config.

I have a requirement in Pipes to pass a GitHub App `token` to the plugin (like we already do with a PAT). It's not feasible/possible for me to expose the private key to the Pipes workspace so I will need to generate the app token centrally and securely distribute to the workspace as required.

So I'm not sure if this is a new issue for this requirement, or just that the solution for this issue requires both approaches:

- Provide the plugin with the information it needs to generate an app token (`app_id`, `installation_id`, `private_key`)
- Generate you own app token and pass to the plugin (`token`)

@johnsmyth FYI on this one further to our earlier discussion.
