### ISSUE TITLE
Added support for plugin authentication using Github OAuth App.

### ISSUE THREAD

**Issue by HikaruEgashira** [turbot/steampipe-plugin-github#431]
**Is your feature request related to a problem? Please describe.**
Yes, I am currently using the gh cli for GitHub authentication, but it is difficult to authenticate because the Steampipe GitHub plugin does not support OAuth tokens (gho_xxx).
https://steampipe.io/changelog/turbot-github-plugin-v0-40-0

**Describe the solution you'd like**
I would like the GitHub plugin to support tokens (gho_xxx) generated by OAuth Apps. Specifically, this can be addressed by updating the token validation logic.
https://github.com/turbot/steampipe-plugin-github/blob/main/github/utils.go#L76-L80

**Describe alternatives you've considered**
I can use other auth methods. (GitHub App or PAT)

**Additional context**
Authentication via OAuth has been made possible as seen here, but it is currently unusable due to the existing token validation. The relevant code can be found here. The issue can be resolved with just an update to the validation, and I am willing to participate in the implementation.

<img width="779" alt="image" src="https://github.com/turbot/steampipe-plugin-github/assets/39324739/f73ae57d-a1f4-4197-bd1e-5b5da6088577">

**Comment by ParthaI** [comment]
Hi @HikaruEgashira, 

We have raised a [PR](https://github.com/turbot/steampipe-plugin-github/pull/432) by addressing this issue.
We have added support for an OAuth access token for GitHub authentication.

It would be great if you would like to give it a try in the PR branch(`issue-431`) and share your feedback.

Testing Steps in the PR Branch(`issue-431`):

- Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-github.git`
- Navigate to the directory: `cd steampipe-plugin-github`
- Switch to the `issue-431` branch: `git checkout issue-431`
- Execute `make`
- Run your query.

If you are running into any further issues, please feel free to let us know.

Thanks!

**Comment by HikaruEgashira** [comment]
Thanks! Commented your PR.
