### ISSUE TITLE
It is not working well with Postgres FDW

### ISSUE THREAD

**Issue by raybittuiq** [turbot/steampipe-plugin-github#453]
**Describe the bug**
When I try to use it with Postgres FDW, it gets connected to the foreign server only in the session when I create the foreign server, after that it does not pick the github credentials either from environment or foreign server config

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
v0.43.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
@raybittuiq apologies for the issue.

Could you please outline the steps to reproduce the error correctly? Please include the relevant commands and errors that you are encountering.

Thanks!!

**Comment by raybittuiq** [comment]
I followed this https://hub.steampipe.io/plugins/turbot/github, here I executed these commands with my github PAT in config

`CREATE EXTENSION IF NOT EXISTS steampipe_postgres_github;
CREATE SERVER steampipe_github FOREIGN DATA WRAPPER steampipe_postgres_github OPTIONS (config 'token = "github_pat");
CREATE SCHEMA github;
IMPORT FOREIGN SCHEMA github FROM SERVER steampipe_github INTO github;`

**Comment by raybittuiq** [comment]
and I got error like this - `db query error: pq: public: rpc error: code = Internal desc = hydrate function tableGitHubMyGistList failed with panic 'token' or 'app_id', 'installation_id' and 'private_key' must be set in the connection configuration. Edit your connection configuration file and then restart Steampipe`

even if I have mentioned the token, it's saying token is not there when I restart the terminal again

**Comment by raybittuiq** [comment]
@misraved I have even appended this statement to the .bashrc file

`export GITHUB_TOKEN=ghp_my_pat`

Still getting the same error

**Comment by ParthaI** [comment]
Hello @raybittuiq,

It seems like when you start a new session, the environment variables set in your `.bashrc` file are not being applied automatically. After making changes to the `.bashrc` file, you'll need to run the command `source ~/.bashrc` in any new terminal session to load the exported values into the environment. Could you please try this and let us know if it resolves the issue?

Additionally, I believe this issue might be related to how your local environment and sessions are being managed, rather than a problem with the plugin itself.

Let us know if this helps!

**Comment by raybittuiq** [comment]
@ParthaI I have done that, also I have written it in .bashrc file, and also on bash shell I am able to print the token with the command `echo $GITHUB_TOKEN` the github token is getting displayed.

**Comment by raybittuiq** [comment]
@ParthaI I think there is some issue with the plugin itself, but yes it's working good as plugin but not working as FDW

**Comment by pskrbasu** [comment]
Hey @raybittuiq Thanks for bringing this to our attention. There is an issue with the Postgres FDW built with Github plugin v0.43.0. I have reproduced the issue where after re-starting the session, the creds are lost. I will look into what is causing this behaviour.

Meanwhile you can try with the v0.42.0. I have verified that it works in that version.
```
/bin/sh -c "$(curl -fsSL https://steampipe.io/install/postgres.sh)" -- github
Enter the version (latest): v0.42.0
```

**Comment by raybittuiq** [comment]
Thanks @pskrbasu the issue is resolved now.

**Comment by ParthaI** [comment]
Hello @raybittuiq, I’m closing this issue as it has been resolved. If you experience any further problems, please don't hesitate to open a new issue. Thanks!
