### ISSUE TITLE
Expose repository custom properties.

### ISSUE THREAD

**Issue by christophla** [turbot/steampipe-plugin-github#456]
**Is your feature request related to a problem? Please describe.**

Repository custom properties are not currently included in the `github_repository` table. These would be very useful for displaying additional metadata within Steampipe/Powerpipe dashboards.

From the [Github API Schema (2022-11-18)](https://docs.github.com/en/rest/repos/custom-properties?apiVersion=2022-11-28)
``` json
"custom_properties": {
  "type": "object",
  "description": "The custom properties that were defined for the repository. The keys are the custom property names, and the values are the corresponding custom property values.",
  "additionalProperties": true
 }
```

**Describe the solution you'd like**

I would like to be able to query against the custom properties for a repository. I'm not sure what the syntax would be, but it could be based off of the current json approach. (https://steampipe.io/docs/sql/querying-json)

``` sql
SELECT * FROM github_repository WHERE custom_properties ->> 'project' = 'my-project'
```

``` sql
SELECT custom_properties["project"] FROM github_repository WHERE repository_full_name = 'my-repo'
```

If this isn't feasible, adding a `github_repository_properties` table may be beneficial.

``` sql
SELECT project, data_class, component FROM github_repository_properties WHERE repository_full_name = 'my-repo'
```

**Describe alternatives you've considered**
I have not been able to query for custom properties within the steampipe environment.

**Additional context**
None

**Comment by misraved** [comment]
Hello @priyavratamohan, 

How is it going so far? Do you need any help with the issue?

**Comment by misraved** [comment]
Hello @priyavratamohan ,

We haven’t received a response in a while, so we’re going to close this issue for now. If this is still a concern or if you have additional details to share, please don’t hesitate to reopen the issue, and we’ll be happy to assist you further.

Thank you for your understanding, and we appreciate your contributions!!
