### ISSUE TITLE
Add table github_dependency

### ISSUE THREAD

**Issue by captn3m0** [turbot/steampipe-plugin-github#46]
GitHub GraphQL API supports `DependencyGraph*` resources for quite a few package managers now.

https://docs.github.com/en/graphql/reference/objects#dependencygraphdependency

Doesn't look like `go-github` will be supporting it (as that relies on the REST API).

**Comment by rajlearner17** [comment]
@captn3m0 appreciate your interest and detailed information. Thank you!!. We will definitely be checking this.  Pls, keep us posted for further observation.

**Comment by captn3m0** [comment]
not stale.

**Comment by jeremie0** [comment]
Rest API support is on the GitHub roadmap now https://github.com/github/roadmap/issues/495

**Comment by captn3m0** [comment]
The item on roadmap only covers alerts and updates. The issue was for DependencyGraph which is much more comprehensive (all dependencies of a repo, irrespective of vulnerability status).

**Comment by cbruno10** [comment]
Hey @captn3m0 , sorry for the radio silence on this one.

I haven't used https://github.com/shurcooL/githubv4 personally, but it looks promising and I'd be open to introducing that package to this plugin for better GraphQL querying support for new/existing tables. If that package isn't sufficient, I'd also be open to querying the GraphQL API directly, similar to what the [lyft/cartography](https://github.com/lyft/cartography/tree/master/cartography/intel/github) does, along with our [Turbot plugin](https://hub.steampipe.io/plugins/turbot/turbot), e.g., https://github.com/turbot/steampipe-plugin-turbot/blob/main/turbot/table_turbot_resource.go.

If anyone is interested in trying to add new tables using the `shurcool/githubv4` repo or hitting the GraphQL API directly, we'd be happy to work with them on the design process, review any incoming PRs, and answer any questions they have.

**Comment by captn3m0** [comment]
not stale

**Comment by cbruno10** [comment]
Hey @captn3m0 , just so you're aware, we're not actively looking at adding this table as we're currently focusing on other priorities. I believe the resources and links I've included in my previous comment can help anyone looking to implement this table, but if not, we're happy to help/provide more guidance.

The `stale` label will be re-attached every 30 days as per our workflow, so if you'd like to keep this open for more community visibility, please feel free to continue commenting (just like above). Thanks!
