### ISSUE TITLE
github_user RPC error

### ISSUE THREAD

**Issue by petewilcock** [turbot/steampipe-plugin-github#6]
Currenting throwing an error on github_user table as follows:

```
> select * from github_user
Error: pq: rpc error: code = Internal desc = 'List' call requires an '=' qual for column: login
```
Same when using a SQL client with the service. Confirmed the Access Token has the required scopes. 

Also small docs note: https://hub.steampipe.io/plugins/turbot/github

scope for `read:email` should be `user:email` I think?

**Comment by e-gineer** [comment]
The `github_user` table does not list all users via the API - there is not currently an efficient way to limit the results in a useable way. As a result, you must specify a user `login` in a where or you will get no results.

That error message could be a lot more friendly though, I've opened an issue for that here - https://github.com/turbot/steampipe/issues/80

I've fixed the `user:email` perm in our docs for the next version.

Thanks for the info, please let us know if you see anything else!
