### ISSUE TITLE
Support for GitHub Enterprise

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-github#70]
It would be great if the GitHub plugin supported GitHub Enterprise. This would be mostly a change to the config and connection setup to allow a custom host etc.

After development, we'll require someone with access to GitHub Enterprise to help with final testing.

**Comment by e-gineer** [comment]
I've pushed a branch with support for GitHub Enterprise at https://github.com/turbot/steampipe-plugin-github/tree/github-enterprise-support

We'd really appreciate testing from a GitHub Enterprise user! Please let us know how it goes and we can merge back into main.

**Comment by cbruno10** [comment]
Re-opening as https://github.com/turbot/steampipe-plugin-github/pull/160 is open to address this
