### ISSUE TITLE
Add table github_rate_limit

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-plugin-github#72]
I'm having to check mine manually using Postman, would be nice to have this in Steampipe.

**Comment by rajlearner17** [comment]
@judell thanks for raising this, this seems useful. We will start looking into it.

**Comment by judell** [comment]
Here's more context, and something that's actually blocking me right now.

I was using this code to load 88,545 commits into a table that I still have in Steampipe.

```
create table commits as (
  select
    *
  from
    github_commit g
  where
    g.repository_full_name = 'microsoft/vscode'
);
```

So this was clearly possible within the 5K/hr API rate limit. Other things weren't, and I triggered a reset a couple of times. 

Now, the above code only gets ~2200 commits, and costs me about that many calls to get them, per https://api.github.com/rate_limit

```
    "rate": {
        "limit": 5000,
        "used": 2270,
        "remaining": 2730,
        "reset": 1634539423
    }
```

What could have changed? I don't see how it's Steamipe. Could GitHub be punishing me for infractions?
