### ISSUE TITLE
Runtime error on `github_repository` if you pass a non-existent `full_name`

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe-plugin-github#96]
**Describe the bug**
`full_name` is a required key col on `github_repository`, but if you pass one that doesn't exist you get a runtime error:

`rpc error: code = Internal desc = hydrate function tableGitHubRepositoryGet failed with panic runtime error: invalid memory address or nil pointer dereference`

**Steampipe version (`steampipe -v`)**
`v0.9.1`

**Plugin version (`steampipe plugin list`)**
`v0.8.1`

**To reproduce**
`select * from github.github_repository where full_name = 'turbot/steampipez';`

**Expected behavior**
An empty result, an appropriate 404-esque error, or if it's a repo I don't have permission to view, perhaps an error related to that?

**Comment by rajlearner17** [comment]
@MichaelBurgess Thanks for the issue, this is addressed already in [main](https://github.com/turbot/steampipe-plugin-github/commit/1993967bf512789c40cc5afc9dc7ef87d33d9e85) yet to be released. Expected release next week. Marking this closed.
